Fix error id - Service page
TypeError: Cannot destructure property 'id' of '(intermediate value)' as it is null.
    at ei (.next/server/app/(service)/s/[slug]/page.js:1:18130) {
  digest: '450768059'
}